--
-- PostgreSQL database dump
--

\restrict BQ4GlLR3EIEIEBEF51RcEQdIB0lutGFx2UseMwDBfWFlkgqKaXLCzZt3NFHt55s

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 15.14 (Debian 15.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: car; Type: TABLE; Schema: public; Owner: Apurbo
--

CREATE TABLE public.car (
    id bigint NOT NULL,
    color character varying(255),
    engineid bigint,
    maker character varying(255),
    model character varying(255),
    ownerid bigint,
    price double precision NOT NULL,
    seats integer NOT NULL,
    transmission character varying(255),
    year integer NOT NULL
);


ALTER TABLE public.car OWNER TO "Apurbo";

--
-- Name: car_id_seq; Type: SEQUENCE; Schema: public; Owner: Apurbo
--

ALTER TABLE public.car ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cars; Type: TABLE; Schema: public; Owner: Apurbo
--

CREATE TABLE public.cars (
    id bigint NOT NULL,
    color character varying(255),
    fuel_type character varying(255),
    maker character varying(255),
    model character varying(255),
    price double precision NOT NULL,
    seats integer NOT NULL,
    transmission character varying(255),
    year integer NOT NULL,
    engine_id bigint,
    user_id bigint,
    engineid bigint,
    ownerid bigint
);


ALTER TABLE public.cars OWNER TO "Apurbo";

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: Apurbo
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: Apurbo
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO "Apurbo";

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: Apurbo
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO "Apurbo";

--
-- Name: engines; Type: TABLE; Schema: public; Owner: Apurbo
--

CREATE TABLE public.engines (
    id bigint NOT NULL,
    cylinders integer NOT NULL,
    displacement double precision NOT NULL,
    fuel_efficiency double precision NOT NULL,
    fuel_system character varying(255),
    horsepower integer NOT NULL,
    torque double precision NOT NULL,
    turbocharged boolean NOT NULL,
    type character varying(255)
);


ALTER TABLE public.engines OWNER TO "Apurbo";

--
-- Name: engines_id_seq; Type: SEQUENCE; Schema: public; Owner: Apurbo
--

ALTER TABLE public.engines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.engines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: Apurbo
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255),
    cars integer[]
);


ALTER TABLE public.users OWNER TO "Apurbo";

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: Apurbo
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: car; Type: TABLE DATA; Schema: public; Owner: Apurbo
--

COPY public.car (id, color, engineid, maker, model, ownerid, price, seats, transmission, year) FROM stdin;
1	White	5	Toyota	Corolla	1	25000	5	Automatic	2022
2	Red	7	Ford	Mustang	1	45000	4	Manual	2021
3	Blue	8	Honda	Civic	1	27000	5	Automatic	2023
4	Black	1	BMW	X5	1	60000	5	Automatic	2020
5	Silver	2	Tesla	Model 3	1	50000	5	Automatic	2024
6	Grey	7	Audi	A4	1	40000	5	Automatic	2022
\.


--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: Apurbo
--

COPY public.cars (id, color, fuel_type, maker, model, price, seats, transmission, year, engine_id, user_id, engineid, ownerid) FROM stdin;
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: Apurbo
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: Apurbo
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: engines; Type: TABLE DATA; Schema: public; Owner: Apurbo
--

COPY public.engines (id, cylinders, displacement, fuel_efficiency, fuel_system, horsepower, torque, turbocharged, type) FROM stdin;
1	4	1.6	15.2	Direct Injection	150	250.5	t	Petrol
2	4	2	18.5	Common Rail	180	320	t	Diesel
5	0	0	0	Electric Motor	200	400	f	Electric
6	4	1.8	22	Direct Injection + Electric	220	300	t	Hybrid
7	3	1.2	14	Carburetor	130	190	f	Petrol
8	6	3	12.5	Direct Injection	250	450	t	Diesel
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: Apurbo
--

COPY public.users (id, email, first_name, last_name, password, cars) FROM stdin;
\.


--
-- Name: car_id_seq; Type: SEQUENCE SET; Schema: public; Owner: Apurbo
--

SELECT pg_catalog.setval('public.car_id_seq', 6, true);


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: Apurbo
--

SELECT pg_catalog.setval('public.cars_id_seq', 1, false);


--
-- Name: engines_id_seq; Type: SEQUENCE SET; Schema: public; Owner: Apurbo
--

SELECT pg_catalog.setval('public.engines_id_seq', 8, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: Apurbo
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: car car_pkey; Type: CONSTRAINT; Schema: public; Owner: Apurbo
--

ALTER TABLE ONLY public.car
    ADD CONSTRAINT car_pkey PRIMARY KEY (id);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: Apurbo
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: Apurbo
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: engines engines_pkey; Type: CONSTRAINT; Schema: public; Owner: Apurbo
--

ALTER TABLE ONLY public.engines
    ADD CONSTRAINT engines_pkey PRIMARY KEY (id);


--
-- Name: cars ukkfw3goyl3cgwqe10mkeo4txwm; Type: CONSTRAINT; Schema: public; Owner: Apurbo
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT ukkfw3goyl3cgwqe10mkeo4txwm UNIQUE (engine_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: Apurbo
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: cars fkijdkhps4dwsv7r4jkfic2jaue; Type: FK CONSTRAINT; Schema: public; Owner: Apurbo
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT fkijdkhps4dwsv7r4jkfic2jaue FOREIGN KEY (engine_id) REFERENCES public.engines(id);


--
-- Name: cars fkqw4c8e6nqrvy3ti1xj8w8wyc9; Type: FK CONSTRAINT; Schema: public; Owner: Apurbo
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT fkqw4c8e6nqrvy3ti1xj8w8wyc9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict BQ4GlLR3EIEIEBEF51RcEQdIB0lutGFx2UseMwDBfWFlkgqKaXLCzZt3NFHt55s

